const heights = {
  topBar: '52px',
  header: '80px',
  footer: '300px',
  social: '20px',
  hero: '480px',
}

module.exports = {
  purge: ['./src/**/*.tsx'],
  darkMode: false,
  theme: {
    extend: {
      fontFamily: {
        'af-helvetica': ['Helvetica Neue', 'sans-serif'],
      },
      lineHeight: {
        'af-16': '16px',
        'af-18': '18px',
        'af-20': '20px',
        'af-22': '22px',
        'af-24': '24px',
        'af-56': '56px',
      },
      fontSize: {
        'af-2': '2px',
        'af-4': '4px',
        'af-6': '6px',
        'af-8': '8px',
        'af-10': '10px',
        'af-12': '12px',
        'af-14': '14px',
        'af-16': '16px',
        'af-20': '20px',
        'af-24': '24px',
        'af-32': '32px',
        'af-48': '48px',
      },
      textColor: {
        af: {
          base: 'var(--color-text-dark-black)',
          'base-medium': 'var(--color-text-medium-black)',
          'muted-dark': 'var(--color-text-dark-gray)',
          'muted-medium': 'var(--color-text-medium-gray)',
          'muted-light': 'var(--color-text-light-gray)',
          inverted: 'var(--color-text-inverted)',
          fill: 'var(--color-stack-fill)',
        },
      },
      backgroundColor: {
        af: {
          fill: 'var(--color-fill)',
          'fill-gray': 'var(--color-fill-gray)',
          'button-accent': 'var(--color-button-accent)',
          'button-muted': 'var(--color-button-muted)',
          hero: 'var(--color-hero)',
          filters: 'var(--color-button-muted)',
          white: '#FFFFFF',
          footer: 'var(--color-footer)',
        },
      },
      height: {
        header: heights.header,
        footer: heights.footer,
        social: heights.social,
        hero: heights.hero,
        'af-11': '11,67px',
        'af-13': '13,33px',
        'af-22': '22px',
        'af-24': '24px',
        'af-246': '246px',
      },
      width: {
        'af-14': '14px',
        'af-16': '16px',
        'af-24': '24px',
        'af-94': '94px',
        'af-300': '300px',
      },
      maxWidth: {
        'af-510': '510px',
        'af-520': '520px',
        'af-xl': '1056px',
      },
      minHeight: {
        header: heights.header,
        footer: heights.footer,
        content: `calc(100vh - ${heights.header} - ${heights.footer})`,
      },
      maxHeight: {
        'af-22': '22px',
        'af-34': '34px',
        'af-246': '246px',
      },
      margin: {
        'af-8': '8px',
        'af-15': '15px',
        'af-16': '16px',
        'af-20': '20px',
        'af-22': '22px',
        'af-25': '25px',
        'af-26': '26px',
        'af-33': '33px',
        'af-72': '72px',
      },
      padding: {
        'af-8': '8px',
        'af-9': '9px',
        'af-10': '10px',
        'af-16': '16px',
        'af-20': '20px',
        'af-32': '32px',
        'af-33': '33px',
        'af-40': '40px',
        'af-62': '62px',
        'af-72': '72px',
        'af-100': '100px',
      },

      borderRadius: {
        'af-4': '4px',
        'af-8': '8px',
        'af-12': '12px',
      },

      borderRadius: {
        'af-4': '4px',
        'af-8': '8px',
      },

      borderWidth: {
        'af-0': '0px',
        'af-1': '1px',
        'af-2': '2px',
        'af-3': '3px',
        'af-4': '4px',
      },
      space: {
        'af-4': '4px',
        'af-8': '8px',
        'af-10': '10px',
        'af-16': '16px',
        'af-18': '18px',
        'af-20': '20px',
        'af-25': '25px',
        'af-26': '26px',
        'af-29': '29px',
        'af-30': '30px',
      },
      gap: {
        'af-6': '6px',
        'af-8': '8px',
        'af-16': '16px',
        'af-24': '24px',
        'af-36': '36px',
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
